package com.dendnight.basis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dendnight.basis.criteria.UserCriteria;
import com.dendnight.basis.model.User;
import com.dendnight.basis.model.UserExample;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Wed Feb 19 21:29:30 CST 2014
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Tue Feb 18 22:12:45 CST 2014
	 */
	int updateByPrimaryKey(User record);

	/**
	 * 会员数量
	 * 
	 * @param criteria
	 * @return
	 */
	int count(UserCriteria criteria);

	/**
	 * 会员列表
	 * 
	 * @param criteria
	 * @return
	 */
	List<User> list(UserCriteria criteria);
}