package com.dendnight.gallery.model;

public class DataBase64 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_base64.id
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_base64.data
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_base64.id
     *
     * @return the value of t_data_base64.id
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_base64.id
     *
     * @param id the value for t_data_base64.id
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_base64.data
     *
     * @return the value of t_data_base64.data
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_base64.data
     *
     * @param data the value for t_data_base64.data
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}