package com.dendnight.gallery.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public ImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("i.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("i.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("i.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("i.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("i.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("i.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("i.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("i.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("i.id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("i.id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("i.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("i.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("i.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("i.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("i.height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("i.height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("i.height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("i.height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("i.height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("i.height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("i.height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("i.height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("i.height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("i.height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("i.height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("i.height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("i.width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("i.width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("i.width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("i.width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("i.width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("i.width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("i.width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("i.width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("i.width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("i.width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("i.width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("i.width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNull() {
            addCriterion("i.file_size is null");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNotNull() {
            addCriterion("i.file_size is not null");
            return (Criteria) this;
        }

        public Criteria andFileSizeEqualTo(Integer value) {
            addCriterion("i.file_size =", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotEqualTo(Integer value) {
            addCriterion("i.file_size <>", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThan(Integer value) {
            addCriterion("i.file_size >", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("i.file_size >=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThan(Integer value) {
            addCriterion("i.file_size <", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThanOrEqualTo(Integer value) {
            addCriterion("i.file_size <=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeIn(List<Integer> values) {
            addCriterion("i.file_size in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotIn(List<Integer> values) {
            addCriterion("i.file_size not in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeBetween(Integer value1, Integer value2) {
            addCriterion("i.file_size between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("i.file_size not between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("i.format is null");
            return (Criteria) this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("i.format is not null");
            return (Criteria) this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("i.format =", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("i.format <>", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("i.format >", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("i.format >=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("i.format <", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("i.format <=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("i.format like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("i.format not like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("i.format in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("i.format not in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("i.format between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("i.format not between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("i.file_path is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("i.file_path is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("i.file_path =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("i.file_path <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("i.file_path >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("i.file_path >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("i.file_path <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("i.file_path <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("i.file_path like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("i.file_path not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("i.file_path in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("i.file_path not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("i.file_path between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("i.file_path not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("i.created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("i.created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Integer value) {
            addCriterion("i.created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Integer value) {
            addCriterion("i.created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Integer value) {
            addCriterion("i.created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Integer value) {
            addCriterion("i.created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Integer value) {
            addCriterion("i.created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Integer value) {
            addCriterion("i.created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Integer> values) {
            addCriterion("i.created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Integer> values) {
            addCriterion("i.created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Integer value1, Integer value2) {
            addCriterion("i.created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Integer value1, Integer value2) {
            addCriterion("i.created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("i.created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("i.created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("i.created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("i.created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("i.created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("i.created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("i.created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("i.created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("i.created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("i.created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("i.created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("i.created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("i.longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("i.longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("i.longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("i.longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("i.longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("i.longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("i.longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("i.longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("i.longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("i.longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("i.longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("i.longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("i.latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("i.latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("i.latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("i.latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("i.latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("i.latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("i.latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("i.latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("i.latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("i.latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("i.latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("i.latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andCameraBrandIsNull() {
            addCriterion("i.Camera_brand is null");
            return (Criteria) this;
        }

        public Criteria andCameraBrandIsNotNull() {
            addCriterion("i.Camera_brand is not null");
            return (Criteria) this;
        }

        public Criteria andCameraBrandEqualTo(String value) {
            addCriterion("i.Camera_brand =", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandNotEqualTo(String value) {
            addCriterion("i.Camera_brand <>", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandGreaterThan(String value) {
            addCriterion("i.Camera_brand >", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandGreaterThanOrEqualTo(String value) {
            addCriterion("i.Camera_brand >=", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandLessThan(String value) {
            addCriterion("i.Camera_brand <", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandLessThanOrEqualTo(String value) {
            addCriterion("i.Camera_brand <=", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandLike(String value) {
            addCriterion("i.Camera_brand like", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandNotLike(String value) {
            addCriterion("i.Camera_brand not like", value, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandIn(List<String> values) {
            addCriterion("i.Camera_brand in", values, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandNotIn(List<String> values) {
            addCriterion("i.Camera_brand not in", values, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandBetween(String value1, String value2) {
            addCriterion("i.Camera_brand between", value1, value2, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraBrandNotBetween(String value1, String value2) {
            addCriterion("i.Camera_brand not between", value1, value2, "cameraBrand");
            return (Criteria) this;
        }

        public Criteria andCameraModelIsNull() {
            addCriterion("i.Camera_model is null");
            return (Criteria) this;
        }

        public Criteria andCameraModelIsNotNull() {
            addCriterion("i.Camera_model is not null");
            return (Criteria) this;
        }

        public Criteria andCameraModelEqualTo(String value) {
            addCriterion("i.Camera_model =", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelNotEqualTo(String value) {
            addCriterion("i.Camera_model <>", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelGreaterThan(String value) {
            addCriterion("i.Camera_model >", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelGreaterThanOrEqualTo(String value) {
            addCriterion("i.Camera_model >=", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelLessThan(String value) {
            addCriterion("i.Camera_model <", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelLessThanOrEqualTo(String value) {
            addCriterion("i.Camera_model <=", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelLike(String value) {
            addCriterion("i.Camera_model like", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelNotLike(String value) {
            addCriterion("i.Camera_model not like", value, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelIn(List<String> values) {
            addCriterion("i.Camera_model in", values, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelNotIn(List<String> values) {
            addCriterion("i.Camera_model not in", values, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelBetween(String value1, String value2) {
            addCriterion("i.Camera_model between", value1, value2, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andCameraModelNotBetween(String value1, String value2) {
            addCriterion("i.Camera_model not between", value1, value2, "cameraModel");
            return (Criteria) this;
        }

        public Criteria andLensBrandIsNull() {
            addCriterion("i.lens_brand is null");
            return (Criteria) this;
        }

        public Criteria andLensBrandIsNotNull() {
            addCriterion("i.lens_brand is not null");
            return (Criteria) this;
        }

        public Criteria andLensBrandEqualTo(String value) {
            addCriterion("i.lens_brand =", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandNotEqualTo(String value) {
            addCriterion("i.lens_brand <>", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandGreaterThan(String value) {
            addCriterion("i.lens_brand >", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandGreaterThanOrEqualTo(String value) {
            addCriterion("i.lens_brand >=", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandLessThan(String value) {
            addCriterion("i.lens_brand <", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandLessThanOrEqualTo(String value) {
            addCriterion("i.lens_brand <=", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandLike(String value) {
            addCriterion("i.lens_brand like", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandNotLike(String value) {
            addCriterion("i.lens_brand not like", value, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandIn(List<String> values) {
            addCriterion("i.lens_brand in", values, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandNotIn(List<String> values) {
            addCriterion("i.lens_brand not in", values, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandBetween(String value1, String value2) {
            addCriterion("i.lens_brand between", value1, value2, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensBrandNotBetween(String value1, String value2) {
            addCriterion("i.lens_brand not between", value1, value2, "lensBrand");
            return (Criteria) this;
        }

        public Criteria andLensModelIsNull() {
            addCriterion("i.lens_model is null");
            return (Criteria) this;
        }

        public Criteria andLensModelIsNotNull() {
            addCriterion("i.lens_model is not null");
            return (Criteria) this;
        }

        public Criteria andLensModelEqualTo(String value) {
            addCriterion("i.lens_model =", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelNotEqualTo(String value) {
            addCriterion("i.lens_model <>", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelGreaterThan(String value) {
            addCriterion("i.lens_model >", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelGreaterThanOrEqualTo(String value) {
            addCriterion("i.lens_model >=", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelLessThan(String value) {
            addCriterion("i.lens_model <", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelLessThanOrEqualTo(String value) {
            addCriterion("i.lens_model <=", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelLike(String value) {
            addCriterion("i.lens_model like", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelNotLike(String value) {
            addCriterion("i.lens_model not like", value, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelIn(List<String> values) {
            addCriterion("i.lens_model in", values, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelNotIn(List<String> values) {
            addCriterion("i.lens_model not in", values, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelBetween(String value1, String value2) {
            addCriterion("i.lens_model between", value1, value2, "lensModel");
            return (Criteria) this;
        }

        public Criteria andLensModelNotBetween(String value1, String value2) {
            addCriterion("i.lens_model not between", value1, value2, "lensModel");
            return (Criteria) this;
        }

        public Criteria andProgramNameIsNull() {
            addCriterion("i.program_name is null");
            return (Criteria) this;
        }

        public Criteria andProgramNameIsNotNull() {
            addCriterion("i.program_name is not null");
            return (Criteria) this;
        }

        public Criteria andProgramNameEqualTo(String value) {
            addCriterion("i.program_name =", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotEqualTo(String value) {
            addCriterion("i.program_name <>", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameGreaterThan(String value) {
            addCriterion("i.program_name >", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameGreaterThanOrEqualTo(String value) {
            addCriterion("i.program_name >=", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameLessThan(String value) {
            addCriterion("i.program_name <", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameLessThanOrEqualTo(String value) {
            addCriterion("i.program_name <=", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameLike(String value) {
            addCriterion("i.program_name like", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotLike(String value) {
            addCriterion("i.program_name not like", value, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameIn(List<String> values) {
            addCriterion("i.program_name in", values, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotIn(List<String> values) {
            addCriterion("i.program_name not in", values, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameBetween(String value1, String value2) {
            addCriterion("i.program_name between", value1, value2, "programName");
            return (Criteria) this;
        }

        public Criteria andProgramNameNotBetween(String value1, String value2) {
            addCriterion("i.program_name not between", value1, value2, "programName");
            return (Criteria) this;
        }

        public Criteria andDateTakenIsNull() {
            addCriterion("i.date_taken is null");
            return (Criteria) this;
        }

        public Criteria andDateTakenIsNotNull() {
            addCriterion("i.date_taken is not null");
            return (Criteria) this;
        }

        public Criteria andDateTakenEqualTo(Date value) {
            addCriterion("i.date_taken =", value, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenNotEqualTo(Date value) {
            addCriterion("i.date_taken <>", value, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenGreaterThan(Date value) {
            addCriterion("i.date_taken >", value, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenGreaterThanOrEqualTo(Date value) {
            addCriterion("i.date_taken >=", value, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenLessThan(Date value) {
            addCriterion("i.date_taken <", value, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenLessThanOrEqualTo(Date value) {
            addCriterion("i.date_taken <=", value, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenIn(List<Date> values) {
            addCriterion("i.date_taken in", values, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenNotIn(List<Date> values) {
            addCriterion("i.date_taken not in", values, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenBetween(Date value1, Date value2) {
            addCriterion("i.date_taken between", value1, value2, "dateTaken");
            return (Criteria) this;
        }

        public Criteria andDateTakenNotBetween(Date value1, Date value2) {
            addCriterion("i.date_taken not between", value1, value2, "dateTaken");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_image
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 21:41:05 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_image
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}