package com.dendnight.gallery.model;

import java.util.Date;

public class Thumbnail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.id
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.image_id
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.file_path
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.publish
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Integer publish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.created_by
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.created_time
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.updated_by
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.updated_time
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_thumbnail.deleted
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.id
     *
     * @return the value of t_thumbnail.id
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.id
     *
     * @param id the value for t_thumbnail.id
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.image_id
     *
     * @return the value of t_thumbnail.image_id
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.image_id
     *
     * @param imageId the value for t_thumbnail.image_id
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.file_path
     *
     * @return the value of t_thumbnail.file_path
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.file_path
     *
     * @param filePath the value for t_thumbnail.file_path
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.publish
     *
     * @return the value of t_thumbnail.publish
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Integer getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.publish
     *
     * @param publish the value for t_thumbnail.publish
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setPublish(Integer publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.created_by
     *
     * @return the value of t_thumbnail.created_by
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.created_by
     *
     * @param createdBy the value for t_thumbnail.created_by
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.created_time
     *
     * @return the value of t_thumbnail.created_time
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.created_time
     *
     * @param createdTime the value for t_thumbnail.created_time
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.updated_by
     *
     * @return the value of t_thumbnail.updated_by
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.updated_by
     *
     * @param updatedBy the value for t_thumbnail.updated_by
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.updated_time
     *
     * @return the value of t_thumbnail.updated_time
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.updated_time
     *
     * @param updatedTime the value for t_thumbnail.updated_time
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_thumbnail.deleted
     *
     * @return the value of t_thumbnail.deleted
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_thumbnail.deleted
     *
     * @param deleted the value for t_thumbnail.deleted
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}