package com.dendnight.gallery.mapper;

import com.dendnight.gallery.model.DataBase64;
import com.dendnight.gallery.model.DataBase64Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataBase64Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int countByExample(DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int deleteByExample(DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int insert(DataBase64 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int insertSelective(DataBase64 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    List<DataBase64> selectByExampleWithBLOBs(DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    List<DataBase64> selectByExample(DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    DataBase64 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") DataBase64 record, @Param("example") DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") DataBase64 record, @Param("example") DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int updateByExample(@Param("record") DataBase64 record, @Param("example") DataBase64Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int updateByPrimaryKeySelective(DataBase64 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_base64
     *
     * @mbggenerated Sun Feb 23 17:27:56 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(DataBase64 record);
}