package com.dendnight.gallery.mapper;

import com.dendnight.gallery.model.Thumbnail;
import com.dendnight.gallery.model.ThumbnailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThumbnailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int countByExample(ThumbnailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int deleteByExample(ThumbnailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int insert(Thumbnail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int insertSelective(Thumbnail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    List<Thumbnail> selectByExample(ThumbnailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    Thumbnail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int updateByExampleSelective(@Param("record") Thumbnail record, @Param("example") ThumbnailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int updateByExample(@Param("record") Thumbnail record, @Param("example") ThumbnailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int updateByPrimaryKeySelective(Thumbnail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thumbnail
     *
     * @mbggenerated Tue Feb 18 21:41:05 CST 2014
     */
    int updateByPrimaryKey(Thumbnail record);
}